function f = create_feature_struct(num_pnts)
    % f - struct of features
    [f.L,f.P,f.S,f.O,f.A,...
    f.Esum,f.SV,f.Entropy,f.Sm,...
    f.FOFA,f.FOSA,f.SOFA,f.SOSA,...
    f.dotprod,f.angle,...
    f.len_pr,f.len_sc,...
    f.density] = deal(nan(num_pnts,1));
end

